export const REGISTER_USER_SUCCESS = "USER REGISTER SUCCESS";
export const REGISTER_USER_FAILED = "USER REGISTER FAILED";

export const LOGIN_USER_SUCCESS = "USER LOGIN IN SUCCESS";
export const LOGIN_USER_FAILED = "FAIL TO LOGIN";
export const LOGOUT_USER = "USER AS BEEN DISCONNECTED";

export const USER_LOADED = "LOADING USER DATA";
export const USER_LOADED_ERROR = "ERROR AUTHENTICATION USER";

export const SET_ALERT = "SET ALERT";
export const REMOVE_ALERT = "DELETE ALERT";
