export const REGISTER_USER_SUCCESS = "COMPTE UTILISATEUR CRÉE AVEC SUCCESS";
export const REGISTER_USER_FAILED = "ÉCHEC CRÉATION COMPTE UTILISATEUR";

export const LOGIN_USER_SUCCESS = "UTILISATEUR CONNECTÉ AVEC SUCCÈS";
export const LOGIN_USER_FAILED = "ÉCHEC CONNEXION COMPTE UTILISATEUR";
export const USER_PROFILE_CLEAR = "PROFILE UTILISATEUR EFFACÉ";
export const LOGOUT_USER = "UTILISATEUR DÉCONNECTÉ";

export const USER_LOADED = "CHARGEMENT DES DONNÉES UTILISATEUR";
export const USER_LOADED_ERROR = "ÉCHEC AUTHENTIFICATION UTILISATEUR";

export const SET_ALERT = "INSERTION ALERTE";
export const REMOVE_ALERT = "SUPPRESSION ALERTE";
